server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html index.html;

    location = / {
        try_files /index.html =404;
    }

    location / {
        error_page 404 /index.html;
        try_files $uri =404;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|json)$ {
        try_files $uri =404;
    }
}
